engine = ink
title = Lost in New York
author = An Ink Story
description = You're standing on the corner of Broadway and Canal with a dead phone and the world's worst directions.
binary = lostinnewyork.json
source = lostinnewyork.ink
tags = demo
